- name: WSL Dev Environment
  hosts: localhost
  connection: local
  gather_facts: true

  roles:
    - { role: backup, when: enable_backup | default(true) }
    - base
    - { role: brew, when: enable_brew }
    - { role: devtools, when: enable_brew }
    - { role: shell, when: enable_zsh }
    - { role: git, when: enable_git_config | default(true) }
    - { role: python, when: enable_python }
    - { role: go, when: enable_go }
    - { role: node, when: enable_node }
    - { role: docker, when: enable_docker }
    - { role: windows-integration, when: enable_windows_integration | default(true) }
    - { role: sudo, when: enable_passwordless_sudo }