---
# ansible/roles/fonts/tasks/main.yml

- name: Install fonts
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop: "{{ fonts_to_install }}"

- name: Update font cache
  command: fc-cache -fv
  changed_when: false

- name: Display fonts info
  debug:
    msg:
      - "Fonts installed: {{ fonts_to_install | join(', ') }}"
      - "Font cache updated"
