# ansible/roles/go/tasks/main.yml
- name: Install Go via goenv
  shell: |
    goenv install -s 1.22.1
    goenv global 1.22.1
  environment:
    PATH: "/home/linuxbrew/.linuxbrew/bin:{{ ansible_env.PATH }}"